version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: zeragon2_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zeragon2
      POSTGRES_USER: zeragon
      POSTGRES_PASSWORD: 13415968273
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge